//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAKKIMIZDA
    {
        public byte ID { get; set; }
        public string ACIKLAMA { get; set; }
        public string ADRES { get; set; }
        public string OZET { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string LINKEDIN { get; set; }
    }
}
